# This installs flutter dependencies, tests it, builds it for web,
# and deploys it with firebase.
steps:
  # Install
  - name: 'gcr.io/$PROJECT_ID/flutter'
    args: ['pub', 'get']
  # Test
  - name: 'gcr.io/$PROJECT_ID/flutter'
    args: ['test']
  # Build
  - name: 'gcr.io/$PROJECT_ID/flutter'
    entrypoint: '/bin/bash'
    args: ['gcp/deploy/build.sh']
  # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--project', '$PROJECT_ID']
