FROM cirrusci/flutter

# Use flutter web features
RUN flutter channel beta
RUN flutter upgrade
RUN flutter config --enable-web

# Build it
RUN git clone https://github.com/DSC-MtA/unipay-mta.git
RUN cd unipay-mta && flutter build web
