FROM cirrusci/flutter

# Use flutter web features
RUN flutter channel beta
RUN flutter upgrade
RUN flutter config --enable-web

# Build it
RUN git clone https://github.com/DSC-MtA/unipay-mta.git
RUN cd unipay-mta && flutter build web

# Set up npm
RUN sudo apt-get update && sudo apt-get install -y apt-utils && sudo apt-get install -y gpg-agent
RUN curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
RUN sudo apt-get install -y nodejs 
RUN sudo npm --verbose install -g firebase-tools

# Throw it on Firebase
ARG FIREBASE_DEPLOY_KEY
RUN cd unipay-mta && sudo firebase deploy --token $FIREBASE_DEPLOY_KEY
